# Generated by Django 3.1.4 on 2020-12-04 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_image',
            field=models.ImageField(upload_to='employer/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 12, 2, 23, 706169)),
        ),
    ]
