# Generated by Django 3.1.7 on 2021-04-03 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20210403_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 17, 38, 508718)),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 4, 3)),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 15, 17, 38, 511501)),
        ),
    ]
