# Generated by Django 3.1.7 on 2021-04-03 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20210403_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 59, 59, 673733)),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='gratuated_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
