# Generated by Django 3.1.7 on 2021-04-06 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_auto_20210406_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='compnay',
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 11, 49, 27, 426539)),
        ),
    ]
