# Generated by Django 3.1.7 on 2021-04-15 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_add_experience_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumebuilder',
            name='non_technical_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='technical_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 12, 47, 59, 176022)),
        ),
    ]
