# Generated by Django 3.1.7 on 2021-04-15 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_add_technical_and_non_technical_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 17, 5, 15, 183320)),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='non_technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
